### ISSUE TITLE
准备加 perl regex支持不。

### ISSUE THREAD

**Issue by tusooa** [Liutos/LiutCL#1]
如题。

**Comment by Liutos** [comment]
你是说支持Perl扩展过的正则表达式语法？？？

**Comment by tusooa** [comment]
是啊。

**Comment by Liutos** [comment]
有打算，不过打算用C语言的regex.h来实现这个功能，就看regex库有没有包含全部Perl的正则的功能了。

**Comment by tusooa** [comment]
用pcre吧。

**Comment by tusooa** [comment]
其实吾主要说的是添加专门的regex类型。正则输入的时候不需要转义。这样的。

**Comment by Liutos** [comment]
知道这么个库不过一直没去研究过，其实regex.h也不好用→_→

是像Perl那样用//来包括起来的类似形式么？

**Comment by tusooa** [comment]
对啊。还有q{},qq{},qr{},s{}{},qw{},m{},等等

**Comment by tusooa** [comment]
想想c的蛋痛字串处理，--吾用hs得了。

**Comment by Liutos** [comment]
hs？是说Haskell么？

**Comment by tusooa** [comment]
突然想到有了env，namespace就不受限制了。果断用perl.

**Comment by Liutos** [comment]
env？namespace？有什么关联？

**Comment by tusooa** [comment]
http://cpansearch.perl.org/src/GAAS/perl-lisp-0.06/lib/Lisp/Symbol.pm 这个处理symbol的时候是在自己模块添加的。吾就觉得这样有问题。

**Comment by Liutos** [comment]
嗯，我的Symbol是在当前的ENVIRONMENT *变量中添加的，应该等价于你说的模块吧～

**Comment by tusooa** [comment]
不是那意思额。吾说。那Lisp::Symbol是在自己模块里，添加一个hash,放各种symbol。当反复调用，以及嵌套调用的时候，可能会出现symbol不通用的情况。

**Comment by Liutos** [comment]
呃，我表示我没有看懂，抱歉Perl学得不精T_T……

**Comment by tusooa** [comment]
简单地说。就是Lisp::Symbol里是symbol都放到自己模块里的hash里。准备是放到指定env里。

**Comment by Liutos** [comment]
也就是说符号查找表要分开不同的层次存储咯？

**Comment by tusooa** [comment]
吾说放到统一的env里。好。

**Comment by Liutos** [comment]
呃，我觉得没法讨论下去了，我不是很懂兔嫂你在说什么……

**Comment by biergaizi** [comment]
继续挖坟：PCRE 最大的优点是支持 Unicode，`regex.h` 的实现相当受限。

**Comment by Liutos** [comment]
@biergaizi 哦，这个项目已经可以说是死掉的了。

其实我更想自己写一个XD

**Comment by tusooa** [comment]
还是没有看懂之前自己在讲什么x

**Comment by biergaizi** [comment]
没看懂自己 +1
